# # # # # # 
# TerraForm
# # # # # #
.terraform:
  variables:
    TERRAFORM_IMAGE_TAG: 'hashicorp/terraform' 
  image:
    name: $TERRAFORM_IMAGE_TAG
    entrypoint: ["/bin/sh", "-l", "-c"]
  before_script:
    - terraform version
    - set -x

# TF Lint
.tf_format_check:
  extends:
    .terraform
  script:
    - git config --global url."https://gitlab-ci-token:${CI_JOB_TOKEN}@gitlab.com/".insteadOf "ssh://git@gitlab.com/"
    - terraform init -backend=false
    - terraform fmt -check -diff

# TF Validate
.tf_validate_check:
  extends:
    .terraform
  script:
    - git config --global url."https://gitlab-ci-token:${CI_JOB_TOKEN}@gitlab.com/".insteadOf "ssh://git@gitlab.com/"
    - terraform init -backend=false
    - terraform version
    - terraform validate

# TF Security 
.tf_sec_check:
  image:
    name: 'tfsec/tfsec'
    entrypoint: ["/bin/sh", "-l", "-c"]
  #variables:
  #  TFSEC_EXCEPTIONS_FLAG: -e AWS007,AWS009,AWS014,AWS018
  before_script:
    - set -x
  script:
    - tfsec $TFSEC_EXCEPTIONS_FLAG

# TF apply
.tf_plan_template:
  extends:
    .terraform
  script:
    - git config --global url."https://gitlab-ci-token:${CI_JOB_TOKEN}@gitlab.com/".insteadOf "ssh://git@gitlab.com/"
    - terraform version
    - terraform init
    - terraform plan

.tf_plan_ws_template:
  extends:
    .tf_plan_template
  script:
    - unset TF_WORKSPACE
    - git config --global url."https://gitlab-ci-token:${CI_JOB_TOKEN}@gitlab.com/".insteadOf "ssh://git@gitlab.com/"
    - terraform version
    - terraform init -backend-config=bucket=$TF_STATE_BUCKET
    - export TF_WORKSPACE=$CI_PIPELINE_ID
    - terraform plan

# TF apply
.tf_apply_template:
  extends:
    .terraform
  script:
    - git config --global url."https://gitlab-ci-token:${CI_JOB_TOKEN}@gitlab.com/".insteadOf "ssh://git@gitlab.com/"
    - terraform version
    - terraform init
    - terraform apply -auto-approve
  when: manual

# TF destroy
.tf_destroy_template:
  extends:
    .terraform
  script:
    - git config --global url."https://gitlab-ci-token:${CI_JOB_TOKEN}@gitlab.com/".insteadOf "ssh://git@gitlab.com/"
    - terraform version
    - terraform init
    - terraform destroy -auto-approve
  when: manual

.tf_destroy_ws_template:
  extends:
    - .tf_destroy_template
  script:
    - git config --global url."https://gitlab-ci-token:${CI_JOB_TOKEN}@gitlab.com/".insteadOf "ssh://git@gitlab.com/"
    - terraform version
    - terraform init
    - terraform destroy -auto-approve
    - export EMPTY_TF_WORKSPACE=$TF_WORKSPACE 
    - terraform workspace select default
    - terraform workspace delete $EMPTY_TF_WORKSPACE